version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/usr/src/app/uploads
    ports:
      - "4002:4002"
      - "4000:4000"

volumes:
  uploads:
